In [11]:
import torch

x = torch.tensor([1,2,3,4])
# x.shape  形状
# x.dtype  元素类型
# x.ndim   维度
# x.numel()  元素个数

print(x.device)

x = x.to("cuda")
print(x)
print(x.device)


cpu
tensor([1, 2, 3, 4], device='cuda:0')
cuda:0


In [3]:
# 基本运算
import torch

a = torch.tensor([1, 2, 3])
b = torch.tensor([4, 5, 6])

print(a + b)
print(a * b)
print(a @ b)  # 实际上一维改了定义，是内积

x = torch.tensor([[1, 2, 3],
                  [4, 5, 6]])

print(x.shape)
print(x.reshape(3, 2))
print(x[:, 1])

tensor([5, 7, 9])
tensor([ 4, 10, 18])
tensor(32)
torch.Size([2, 3])
tensor([[1, 2],
        [3, 4],
        [5, 6]])
tensor([2, 5])


In [5]:
# Tensor和Numpy的转换
import torch
import numpy as np

x = torch.tensor([1, 2, 3])

y = x.numpy()

print(y)
print(type(y))

a = np.array([4, 5, 6])

b = torch.from_numpy(a)  #torch.from_numpy() 得到的 Tensor 和原 NumPy 数组通常共享底层内存。

print(b)
print(type(b))

[1 2 3]
<class 'numpy.ndarray'>
tensor([4, 5, 6])
<class 'torch.Tensor'>


In [16]:
# requires_grad
import torch

x = torch.tensor(2.0, requires_grad=True)

y = x ** 2

y.backward()

print(x.grad)

print(y.grad_fn) #rad_fn 就是在告诉你：这个 Tensor 是通过什么运算产生的，以及反向传播时该怎么把梯度传回去。


tensor(4.)


In [17]:
# nn.module
import torch
import torch.nn as nn

model = nn.Linear(3, 1)  # 此时参数随机

print(model)
print(model.weight)
print(model.bias)
print(model.weight.shape)
print(model.bias.shape)

Linear(in_features=3, out_features=1, bias=True)
Parameter containing:
tensor([[ 0.1956,  0.5162, -0.1000]], requires_grad=True)
Parameter containing:
tensor([-0.1609], requires_grad=True)
torch.Size([1, 3])
torch.Size([1])


In [ ]:

import torch
import torch.nn as nn

class MyModel(nn.Module):
    def __init__(self):
        super().__init__()
        self.linear = nn.Linear(3, 1)

    def forward(self, x):
        return self.linear(x)

In [8]:
import torch
import torch.nn as nn


x = torch.tensor([
    [1.],
    [2.],
    [3.],
    [4.]
])

target = torch.tensor([
    [3.],
    [5.],
    [7.],
    [9.]
])

model = nn.Linear(1, 1)
loss_fn = nn.MSELoss()

optimizer = torch.optim.SGD(
    model.parameters(),
    lr=0.01
)

print("训练前：")
print(model.weight)
print(model.bias)

for i in range(1000):
    optimizer.zero_grad()

    pred = model(x)

    loss = loss_fn(pred, target)

    loss.backward()

    optimizer.step()

    if i % 10 == 0:
        print(i, loss.item())   # loss.item()把只包含一个元素的 Tensor 转成 Python 数字


print("训练后：")
print(model.weight)
print(model.bias)

训练前：
Parameter containing:
tensor([[-0.8222]], requires_grad=True)
Parameter containing:
tensor([-0.0393], requires_grad=True)
0 75.4815673828125
10 1.953663945198059
20 0.05127616226673126
30 0.002014336409047246
40 0.0006997769232839346
50 0.0006280647357925773
60 0.0005907133454456925
70 0.0005563102895393968
80 0.0005239298334345222
90 0.0004934248281642795
100 0.0004647110472433269
110 0.00043766124872490764
120 0.00041218294063583016
130 0.00038818875327706337
140 0.0003655902110040188
150 0.0003443102177698165
160 0.00032427857513539493
170 0.00030539752333424985
180 0.0002876253565773368
190 0.00027088518254458904
200 0.0002551207144279033
210 0.00024026900064200163
220 0.00022628433362115175
230 0.00021311173622962087
240 0.00020071282051503658
250 0.00018902479496318847
260 0.00017802632646635175
270 0.00016766083717811853
280 0.00015790073666721582
290 0.0001487146073486656
300 0.00014005445700604469
310 0.00013190456957090646
320 0.00012422577128745615
330 0.000117000250611

In [1]:
# dataset和dataloader
import torch
import torch.nn as nn
from torch.utils.data import Dataset, DataLoader


# 1. Dataset
class MyDataset(Dataset):
    def __init__(self):
        self.x = torch.tensor([
            [1.],
            [2.],
            [3.],
            [4.]
        ])

        self.y = torch.tensor([
            [3.],
            [5.],
            [7.],
            [9.]
        ])

    def __len__(self):
        return len(self.x)

    def __getitem__(self, index):
        return self.x[index], self.y[index]


dataset = MyDataset()


# 2. DataLoader
loader = DataLoader(
    dataset,
    batch_size=2,
    shuffle=True
)


# 3. Model
model = nn.Linear(1, 1)

loss_fn = nn.MSELoss()

optimizer = torch.optim.SGD(
    model.parameters(),
    lr=0.01
)


# 4. Training
for epoch in range(100):

    for x_batch, y_batch in loader:

        optimizer.zero_grad()

        pred = model(x_batch)

        loss = loss_fn(pred, y_batch)

        loss.backward()

        optimizer.step()

    if epoch % 10 == 0:
        print(epoch, loss.item())

0 19.240966796875
10 0.009827864356338978
20 0.006251306273043156
30 0.007238022983074188
40 0.001263905200175941
50 0.005790534894913435
60 0.0010434800060465932
70 0.0034125340171158314
80 0.0016513022128492594
90 0.001015593996271491
